### ISSUE TITLE
Differentiating between indexes and IDs

### ISSUE THREAD

**Issue by haudren** [jrl-umi3218/RBDyn#10]
Hello,

A pain point in using SVA/RBDyn is that it is not very clear when and/or why one should use joint (or body) IDs over indexes. For example, even recently @stanislas-brossette found a bug related to computing a jacobian using an index rather than an id.

To alleviate the problem, I started to make id and index two separate classes using boost's `strong_typedef` macro on my [fork](https://github.com/haudren/RBDyn/tree/topic/diff-id-index). However, I am now wondering if IDs should be exposed in the API:
- The main reason to have IDs is to be able to convert configurations between different MultiBodies that have been generated from the same MultiBodyGraph.
- The Jacobian takes an ID as parameter but throws it away immediately
- Most Tasks take an ID to compute a Jacobian but throw it away similarly

Thus, I wonder if would not be simpler to simply drop the IDs from the public API and only expose the indexes.

@jorisv : Is there a fundamental design problem that I missed ?
@bchretien : I know you are using quite a bit of robots created with different roots, do you see any problem with the above ?

Cheers,
Hervé

**Comment by bchretien** [comment]
Well I think that was the first time I mixed up indices/ids, since `mc_rbdyn`'s `createRobotWithBase` expects the base id for the call to `MultiBodyGraph ::makeMultiBody` (see [here](https://github.com/jorisv/RBDyn/blob/1121591371b00e0dd737528f627c29dc5a97091a/src/MultiBodyGraph.h#L170)). Apparently you missed that class on your fork, and that one only deals with ids as far as I can tell.

**Comment by haudren** [comment]
You're right, (my fork is still very much WIP): people who want to build a robot "from scratch" need to deal with ids and indexes. There is simply no other way around it as indexes are created when creating a robot whereas ids are created per-joint. Thus, IDs can be reused across robots with different bases whereas index 0 is _always_ the root joint.

But, once you created the robot, is there really any need to expose the IDs ? I think most users in our case will mainly create a robot and use the resulting `MultiBody` and `MultiBodyConfig` to implement their controller/algorithm.

**Comment by bchretien** [comment]
In order to change the root body, I do need to have access to the ids, so confusion between indices and ids are still possible, even if we were to force the use of indices in other higher-level parts of the API. Thus I'm also in favor of typed ids/indices.

As for consistency in parts of the API that do not have anything to do with `MultiBodyGraph`, it should clearly be addressed, unless there were some good reasons for using both indices and ids (performance?).

**Comment by gergondet** [comment]
After discussing with Herve (unless we are missing something regarding the `index`/`id` dichotomy), it seems that:
- `id` should be strongly typed (i.e. no explicit cast to and from `int`) and used only where `index` are not available (e.g. `MultiBodyGraph` or accessible through `Joint`/`Body` for those who would build a `MultiBody` from scratch). This would trigger an error if you try to use an index as an id and vice-versa. There is also nothing performance-critic that uses `id`
- keep `index` as-is
- switch to `index` everywhere else (i.e. `Jacobian` for RBDyn but almost everything that uses a `Jacobian` in `Task` also)

The last point should trigger a compilation error as most would do `int bodyId = robot.bodyIdByName('foo'); auto task = Task(mb, id);` or some variant that would fail.

Cheers,

**Comment by jorisv** [comment]
> Thus, I wonder if would not be simpler to simply drop the IDs from the public API and only expose the indexes.

If I understand well what you say you want to only use index to generate jacobian or tasks ?
As you say in you first point ONE use of ID is to have a consistent joints and bodies identifier between MultiBody generated from the same MultiBodyGraph.
The other use (and the most important) is to have a consistent joints and bodies identifier for a specific robot.  Indexes are dependent of the joints and bodies input order to MultiBodyGraph. If one day somebody change this order all your indexes will by changed.

One problem with numeric ID is that URDF don't support them. They where useful a long time ago when we use amelif robot description file format.

Since a lot of people mistake numeric ID with indexes and URDF don't support them my solution would be to remove numeric ID and only use name as joints and bodies identifier.

Do you see any issue with that ?

**Comment by haudren** [comment]
Thanks, I had forgotten about that. I think everyone is using URDF these days, so the usefulness of numerical IDs is gone in my opinion. Moreover, the other formats we might encounter are VRML which has numerical and text ID, SDF which has required text ID and COLLADA which at least supports text ID.

Anyhow, as of now most people do something along the lines of:

``` python
id1 = robot.jointIdByName("JOINT1")
id1 = robot.jointIdByName("JOINT2")
task1 = positionTask( ..., id1, ...)
task2 = orientationTask( ..., id2, ...)
```

And so switching to using names everywhere would simplify the code greatly and reduce the possibility of error.

**Comment by jorisv** [comment]
In the future, if a robot description format only support numeric ID we can still convert it to string so this choice don't screw us.
Python binding will still be simple and we avoid boost dependencies.

So if nobody see any complication I would appreciate such patch.

**Comment by haudren** [comment]
I started working on it on a new [branch](https://github.com/haudren/RBDyn/tree/topic/textual-id). I will open a new pull request whenever I get all tests to pass. I am quite satisfied by this work as it clearly simplifies the API by differentiating between id/index and removes the redundancy id/name.

Cheers,
Hervé
